"""
Advanced Curiosity Engine - Autonomous Learning System (PRODUCTION VERSION)
✔ Safe operation
✔ Smart suggestion generation
✔ Task-based recommendations
✔ Learning from user actions
✔ Feedback integration
✔ Memory integration
✔ Web research capability
✔ Fixed attribute errors
✔ Enhanced stability
"""

import asyncio
import random
import time
import uuid
from typing import Dict, List, Any, Optional, Set
from enum import Enum
from datetime import datetime
from dataclasses import dataclass, field

from ..utils.logger import logger


def _create_web_researcher():
    from ..automation.web_researcher import WebResearcher

    return WebResearcher()


def _create_memory_manager():
    from ..memory.memory_manager import MemoryManager

    return MemoryManager()


class CuriosityType(Enum):
    EXPLORATION = "exploration"
    LEARNING = "learning"
    VERIFICATION = "verification"
    EXPANSION = "expansion"
    SUGGESTION = "suggestion"
    OPTIMIZATION = "optimization"


class SuggestionPriority(Enum):
    HIGH = 1
    MEDIUM = 2
    LOW = 3


@dataclass
class CuriosityItem:
    topic: str
    source: str
    curiosity_type: CuriosityType
    priority: int = 2
    created_at: datetime = field(default_factory=datetime.now)
    explored: bool = False
    result: Optional[Dict[str, Any]] = None


@dataclass
class CuriositySuggestion:
    """Suggestion generated by curiosity engine"""

    suggestion_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    description: str = ""
    suggestion_type: CuriosityType = CuriosityType.SUGGESTION
    priority: SuggestionPriority = SuggestionPriority.MEDIUM
    confidence: float = 0.5
    context: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)
    expires_at: Optional[datetime] = None
    is_taken: bool = False
    feedback: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "suggestion_id": self.suggestion_id,
            "title": self.title,
            "description": self.description,
            "type": self.suggestion_type.value,
            "priority": self.priority.value,
            "confidence": self.confidence,
            "context": self.context,
            "created_at": self.created_at.isoformat(),
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "is_taken": self.is_taken,
            "tags": self.tags,
        }


class CuriosityEngine:
    def __init__(self, curiosity_level: float = 0.7):
        self.curiosity_level = max(0, min(1, curiosity_level))

        self.queue: List[CuriosityItem] = []
        self.explored_topics: Set[str] = set()
        self.active_suggestions: List[CuriositySuggestion] = []
        self.suggestion_history: List[CuriositySuggestion] = []

        self.learning_history: List[Dict[str, Any]] = []
        self.exploration_count = 0
        self.suggestion_count = 0

        # Created lazily when exploration actually needs web research.
        self.researcher = None

        try:
            self.memory = _create_memory_manager()
        except Exception as e:
            logger.warning(f"MemoryManager init failed: {e}")
            self.memory = None

        self._running = False
        self.system = None  # 🔥 injected externally (for idle check)

        # Task tracking
        self.current_user_task: Optional[str] = None
        self.current_user_action: Optional[str] = None  # FIXED: Added missing attribute
        self.user_action_history: List[Dict[str, Any]] = []
        self.task_patterns: Dict[str, int] = {}

        # Cooldown tracking
        self._last_suggestion_time = 0
        self._last_exploration_time = 0
        self._suggestion_cooldown = 30  # seconds between suggestions
        self._exploration_cooldown = 60  # seconds between explorations

        # Knowledge base
        self.knowledge_base: Dict[str, Any] = {}

        # Performance tracking
        self._insights_generated = 0
        self._last_heartbeat = time.time()

        logger.info(f"CuriosityEngine initialized with level {curiosity_level}")

    def _ensure_researcher(self):
        if self.researcher is not None:
            return self.researcher

        try:
            self.researcher = _create_web_researcher()
        except Exception as e:
            logger.warning(f"WebResearcher init failed: {e}")
            self.researcher = None

        return self.researcher

    # ------------------------
    # ADD TOPIC
    # ------------------------
    def add_curiosity(
        self,
        topic: str,
        source: str,
        ctype: CuriosityType = CuriosityType.EXPLORATION,
        priority: int = 2,
    ) -> None:
        """
        Add curiosity item safely (optimized + production-grade)
        """

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not topic or not isinstance(topic, str):
                return

            topic = topic.strip()
            if not topic:
                return

            # normalize topic for deduplication
            topic_key = topic.lower()

            # ------------------------
            # 🔁 DUPLICATE CHECK (CRITICAL FIX)
            # ------------------------
            if topic_key in (
                t.lower() for t in getattr(self, "explored_topics", set())
            ):
                return

            if any(
                getattr(item, "topic", "").lower() == topic_key
                for item in getattr(self, "queue", [])
            ):
                return

            # ------------------------
            # 🔥 PRIORITY NORMALIZATION
            # ------------------------
            try:
                priority = int(priority)
                priority = max(1, min(5, priority))  # clamp 1–5
            except Exception:
                priority = 2

            # ------------------------
            # 🔥 SAFE ENUM HANDLING
            # ------------------------
            if not isinstance(ctype, CuriosityType):
                ctype = CuriosityType.EXPLORATION

            # ------------------------
            # 🔥 CREATE ITEM
            # ------------------------
            item = CuriosityItem(
                topic=topic,
                source=source or "unknown",
                curiosity_type=ctype,
                priority=priority,
            )

            # ------------------------
            # 🔥 INSERT (PRIORITY SORTED)
            # ------------------------
            self.queue.append(item)

            try:
                # keep queue sorted by priority (lower = higher priority)
                self.queue.sort(key=lambda x: getattr(x, "priority", 2))
            except Exception:
                pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self._insights_generated = getattr(self, "_insights_generated", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(f"➕ Added curiosity: {topic} (priority={priority})")
            except Exception:
                pass

        except Exception as e:
            try:
                logger.warning(f"⚠ Failed to add curiosity '{topic}': {e}")
            except Exception:
                pass

    # ------------------------
    # SUGGESTION GENERATION
    # ------------------------
    async def generate_suggestions(
        self, context: str, limit: int = 3
    ) -> List[CuriositySuggestion]:
        """
        Generate suggestions safely (optimized + production-grade)
        """

        import time
        from datetime import datetime

        suggestions: List[CuriositySuggestion] = []

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not context or not isinstance(context, str):
                return []

            context = context.strip()
            if not context:
                return []

            now = time.time()

            # ------------------------
            # ⏱️ COOLDOWN (CRITICAL FIX)
            # ------------------------
            if now - getattr(self, "_last_suggestion_time", 0) < getattr(
                self, "_suggestion_cooldown", 0
            ):
                return []

            context_lower = context.lower()

            # ------------------------
            # 🔁 HELPER: ADD SAFE SUGGESTION
            # ------------------------
            def add_suggestion(s: CuriositySuggestion):
                if len(suggestions) >= limit:
                    return

                # deduplicate by title
                if any(existing.title == s.title for existing in suggestions):
                    return

                suggestions.append(s)

            # ------------------------
            # 🔥 PATTERN-BASED SUGGESTIONS
            # ------------------------
            if any(k in context_lower for k in ["code", "programming", "python"]):
                add_suggestion(
                    CuriositySuggestion(
                        title="Improve Code Quality",
                        description="Consider adding error handling, comments, or optimizing performance.",
                        suggestion_type=CuriosityType.OPTIMIZATION,
                        priority=SuggestionPriority.MEDIUM,
                        confidence=0.75,
                        tags=["coding", "optimization"],
                    )
                )

                add_suggestion(
                    CuriositySuggestion(
                        title="Learn Best Practices",
                        description="Explore coding best practices for your current programming language.",
                        suggestion_type=CuriosityType.LEARNING,
                        priority=SuggestionPriority.LOW,
                        confidence=0.65,
                        tags=["learning", "best_practices"],
                    )
                )

            if any(k in context_lower for k in ["research", "search", "find"]):
                add_suggestion(
                    CuriositySuggestion(
                        title="Deeper Research",
                        description="Would you like me to search for more comprehensive information?",
                        suggestion_type=CuriosityType.EXPANSION,
                        priority=SuggestionPriority.HIGH,
                        confidence=0.85,
                        tags=["research", "expansion"],
                    )
                )

            if any(k in context_lower for k in ["learn", "study"]):
                add_suggestion(
                    CuriositySuggestion(
                        title="Related Topics",
                        description=f"Explore topics related to '{context[:50]}' for deeper understanding.",
                        suggestion_type=CuriosityType.LEARNING,
                        priority=SuggestionPriority.MEDIUM,
                        confidence=0.7,
                        tags=["learning", "related_topics"],
                    )
                )

            if any(k in context_lower for k in ["analyze", "data"]):
                add_suggestion(
                    CuriositySuggestion(
                        title="Data Visualization",
                        description="Consider visualizing your data for better insights.",
                        suggestion_type=CuriosityType.OPTIMIZATION,
                        priority=SuggestionPriority.MEDIUM,
                        confidence=0.7,
                        tags=["data", "visualization"],
                    )
                )

            # ------------------------
            # 🧠 MEMORY-BASED SUGGESTIONS
            # ------------------------
            try:
                memory_suggestions = await self._generate_memory_based_suggestions()
                for s in memory_suggestions or []:
                    if isinstance(s, CuriositySuggestion):
                        add_suggestion(s)
            except Exception:
                pass

            # ------------------------
            # 🔥 QUEUE-BASED SUGGESTIONS
            # ------------------------
            if getattr(self, "queue", None):
                for item in self.queue[:limit]:
                    if len(suggestions) >= limit:
                        break

                    try:
                        add_suggestion(
                            CuriositySuggestion(
                                title=f"Explore: {item.topic[:50]}",
                                description=f"Based on your interests, explore {item.topic}.",
                                suggestion_type=getattr(
                                    item, "curiosity_type", CuriosityType.EXPLORATION
                                ),
                                priority=(
                                    SuggestionPriority(item.priority)
                                    if 1 <= item.priority <= 3
                                    else SuggestionPriority.MEDIUM
                                ),
                                confidence=float(getattr(self, "curiosity_level", 0.5)),
                                tags=[
                                    "exploration",
                                    getattr(item, "source", "unknown"),
                                ],
                            )
                        )
                    except Exception:
                        continue

            # ------------------------
            # 🔥 FINAL LIMIT
            # ------------------------
            suggestions = suggestions[:limit]

            # ------------------------
            # ⏳ EXPIRATION
            # ------------------------
            expires = datetime.now().replace(hour=23, minute=59, second=59)
            for s in suggestions:
                try:
                    s.expires_at = expires
                except Exception:
                    pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            self._last_suggestion_time = now
            self.suggestion_count = getattr(self, "suggestion_count", 0) + len(
                suggestions
            )
            self._insights_generated = getattr(self, "_insights_generated", 0) + len(
                suggestions
            )

            # ------------------------
            # 🔁 ACTIVE STORE (SAFE)
            # ------------------------
            try:
                self.active_suggestions = getattr(self, "active_suggestions", [])
                self.active_suggestions.extend(suggestions)
            except Exception:
                pass

            # ------------------------
            # 🧹 CLEANUP
            # ------------------------
            try:
                self._clean_expired_suggestions()
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.info(f"Generated {len(suggestions)} suggestions")
            except Exception:
                pass

            return suggestions

        except Exception as e:
            try:
                logger.error(f"Suggestion generation failed: {e}")
            except Exception:
                pass

            return []

    async def _generate_memory_based_suggestions(self) -> List[CuriositySuggestion]:
        """
        Generate suggestions from memory safely (optimized + production-grade)
        """

        suggestions: List[CuriositySuggestion] = []

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            memory = getattr(self, "memory", None)
            if not memory or not hasattr(memory, "get_recent"):
                return []

            # ------------------------
            # 🔥 FETCH MEMORY (SAFE)
            # ------------------------
            try:
                recent = await memory.get_recent(10)
            except Exception:
                return []

            if not recent or not isinstance(recent, list):
                return []

            # ------------------------
            # 🔁 ANALYZE PATTERNS
            # ------------------------
            topic_counts = {}

            for entry in recent:
                if not isinstance(entry, dict):
                    continue

                topic = entry.get("topic") or entry.get("type")
                if not topic or not isinstance(topic, str):
                    continue

                topic_key = topic.strip().lower()
                if not topic_key:
                    continue

                topic_counts[topic_key] = topic_counts.get(topic_key, 0) + 1

            if not topic_counts:
                return []

            # ------------------------
            # 🔥 SELECT BEST TOPIC (SMART FIX)
            # ------------------------
            sorted_topics = sorted(
                topic_counts.items(), key=lambda x: x[1], reverse=True
            )

            explored = {t.lower() for t in getattr(self, "explored_topics", set())}

            for topic, count in sorted_topics:

                if count < 3:
                    continue

                if topic in explored:
                    continue

                # ------------------------
                # 🔥 BUILD SUGGESTION
                # ------------------------
                try:
                    suggestion = CuriositySuggestion(
                        title=f"Deepen Knowledge: {topic.capitalize()}",
                        description=f"You've shown repeated interest in {topic}. Want to explore it deeper?",
                        suggestion_type=CuriosityType.EXPANSION,
                        priority=SuggestionPriority.MEDIUM,
                        confidence=min(0.9, 0.5 + (count * 0.1)),
                        tags=["memory_based", topic],
                    )

                    suggestions.append(suggestion)
                    break  # limit to one

                except Exception:
                    continue

            return suggestions

        except Exception as e:
            try:
                logger.debug(f"Memory-based suggestion error: {e}")
            except Exception:
                pass

            return []

    def _clean_expired_suggestions(self):
        """Remove expired suggestions"""
        now = datetime.now()
        self.active_suggestions = [
            s
            for s in self.active_suggestions
            if s.expires_at is None or s.expires_at > now
        ]

        # Also clean history (keep last 100)
        if len(self.suggestion_history) > 100:
            self.suggestion_history = self.suggestion_history[-100:]

    async def get_suggestions_for_task(
        self, task: str, limit: int = 3
    ) -> List[CuriositySuggestion]:
        """Get suggestions specifically for a task"""
        return await self.generate_suggestions(task, limit)

    async def take_suggestion(
        self, suggestion_id: str, feedback: Optional[str] = None
    ) -> bool:
        """
        Mark a suggestion as taken safely (optimized + production-grade)
        """

        from datetime import datetime

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not suggestion_id or not isinstance(suggestion_id, str):
                return False

            suggestions = getattr(self, "active_suggestions", [])
            if not suggestions:
                return False

            # ------------------------
            # 🔍 FIND SUGGESTION (SAFE)
            # ------------------------
            target = None
            for suggestion in suggestions:
                if getattr(suggestion, "suggestion_id", None) == suggestion_id:
                    target = suggestion
                    break

            if not target:
                return False

            # ------------------------
            # 🔥 UPDATE STATE
            # ------------------------
            try:
                target.is_taken = True
                target.feedback = feedback
                target.taken_at = datetime.now().isoformat()
            except Exception:
                pass

            # ------------------------
            # 🔁 SAFE REMOVE (CRITICAL FIX)
            # ------------------------
            try:
                self.active_suggestions = [
                    s
                    for s in suggestions
                    if getattr(s, "suggestion_id", None) != suggestion_id
                ]
            except Exception:
                pass

            # ------------------------
            # 📦 HISTORY STORE
            # ------------------------
            try:
                self.suggestion_history = getattr(self, "suggestion_history", [])
                self.suggestion_history.append(target)
            except Exception:
                pass

            # ------------------------
            # 🧠 LEARNING HISTORY
            # ------------------------
            try:
                self.learning_history = getattr(self, "learning_history", [])
                self.learning_history.append(
                    {
                        "type": "suggestion_taken",
                        "suggestion_id": suggestion_id,
                        "title": getattr(target, "title", None),
                        "feedback": feedback,
                        "timestamp": datetime.now().isoformat(),
                    }
                )
            except Exception:
                pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.taken_suggestions = getattr(self, "taken_suggestions", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.info(
                    f"✅ Suggestion taken: {getattr(target, 'title', suggestion_id)}"
                )
            except Exception:
                pass

            return True

        except Exception as e:
            try:
                logger.error(f"❌ Failed to take suggestion: {e}")
            except Exception:
                pass

            return False

    async def dismiss_suggestion(self, suggestion_id: str) -> bool:
        """
        Dismiss a suggestion safely (optimized + production-grade)
        """

        from datetime import datetime

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not suggestion_id or not isinstance(suggestion_id, str):
                return False

            suggestions = getattr(self, "active_suggestions", [])
            if not suggestions:
                return False

            # ------------------------
            # 🔍 FIND TARGET
            # ------------------------
            target = None
            for s in suggestions:
                if getattr(s, "suggestion_id", None) == suggestion_id:
                    target = s
                    break

            if not target:
                return False

            # ------------------------
            # 🔁 SAFE REMOVE (CRITICAL FIX)
            # ------------------------
            try:
                self.active_suggestions = [
                    s
                    for s in suggestions
                    if getattr(s, "suggestion_id", None) != suggestion_id
                ]
            except Exception:
                pass

            # ------------------------
            # 📦 OPTIONAL HISTORY (UPGRADE)
            # ------------------------
            try:
                self.dismissed_suggestions = getattr(self, "dismissed_suggestions", [])
                self.dismissed_suggestions.append(
                    {
                        "suggestion_id": suggestion_id,
                        "title": getattr(target, "title", None),
                        "timestamp": datetime.now().isoformat(),
                    }
                )
            except Exception:
                pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.dismissed_count = getattr(self, "dismissed_count", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(
                    f"🗑️ Suggestion dismissed: {getattr(target, 'title', suggestion_id)}"
                )
            except Exception:
                pass

            return True

        except Exception as e:
            try:
                logger.error(f"❌ Failed to dismiss suggestion: {e}")
            except Exception:
                pass

            return False

    async def get_active_suggestions(self) -> List[Dict[str, Any]]:
        """Get all active suggestions"""
        self._clean_expired_suggestions()
        return [s.to_dict() for s in self.active_suggestions]

    # ------------------------
    # TASK AND ACTION TRACKING
    # ------------------------
    async def update_current_task(self, task: str) -> None:
        """
        Update current user task safely (optimized + production-grade)
        """

        from datetime import datetime

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if task is not None and not isinstance(task, str):
                return

            task = (task or "").strip()

            # ------------------------
            # 🔁 NORMALIZATION
            # ------------------------
            task_key = task.lower() if task else None

            old_task = getattr(self, "current_user_task", None)

            # ------------------------
            # 🔥 UPDATE STATE
            # ------------------------
            self.current_user_task = task
            self.current_user_action = task  # keep both in sync

            # ------------------------
            # 📊 PATTERN TRACKING (SAFE)
            # ------------------------
            if task_key:
                try:
                    self.task_patterns = getattr(self, "task_patterns", {})
                    self.task_patterns[task_key] = (
                        self.task_patterns.get(task_key, 0) + 1
                    )
                except Exception:
                    pass

            # ------------------------
            # 📜 ACTION HISTORY (SAFE)
            # ------------------------
            try:
                self.user_action_history = getattr(self, "user_action_history", [])
                self.user_action_history.append(
                    {
                        "type": "task_change",
                        "old_task": old_task,
                        "new_task": task,
                        "timestamp": datetime.now().isoformat(),
                    }
                )

                # 🔥 optional limit (memory safety)
                if len(self.user_action_history) > 500:
                    self.user_action_history = self.user_action_history[-500:]
            except Exception:
                pass

            # ------------------------
            # 🧠 SMART SUGGESTION TRIGGER (IMPROVED)
            # ------------------------
            if task and len(task) > 10:
                try:
                    await self.generate_suggestions(task, limit=2)
                except Exception:
                    pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.task_updates = getattr(self, "task_updates", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(f"🔄 Current task updated: {task}")
            except Exception:
                pass

        except Exception as e:
            try:
                logger.error(f"❌ Failed to update task: {e}")
            except Exception:
                pass

    async def record_action(self, action: str, result: Any = None) -> None:
        """
        Record user action safely (optimized + production-grade)
        """

        from datetime import datetime

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not action or not isinstance(action, str):
                return

            action = action.strip()
            if not action:
                return

            # ------------------------
            # 🔁 NORMALIZATION
            # ------------------------
            action_key = action.lower()

            # ------------------------
            # 🔥 UPDATE CURRENT ACTION
            # ------------------------
            self.current_user_action = action

            # ------------------------
            # 📜 SAFE HISTORY APPEND
            # ------------------------
            try:
                self.user_action_history = getattr(self, "user_action_history", [])

                entry = {
                    "type": "action",
                    "action": action,
                    "action_key": action_key,
                    "result": str(result)[:200] if result is not None else None,
                    "timestamp": datetime.now().isoformat(),
                }

                self.user_action_history.append(entry)

                # 🔥 HARD LIMIT (CRITICAL FIX)
                max_history = 200
                if len(self.user_action_history) > max_history:
                    self.user_action_history = self.user_action_history[-max_history:]

            except Exception:
                pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.actions_recorded = getattr(self, "actions_recorded", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 🧠 PATTERN ANALYSIS (SAFE + CONTROLLED)
            # ------------------------
            try:
                history_len = len(self.user_action_history)

                # every 10 actions but avoid spam
                if history_len % 10 == 0 and history_len > 0:
                    await self._analyze_action_patterns()

            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(f"🧠 Action recorded: {action}")
            except Exception:
                pass

        except Exception as e:
            try:
                logger.error(f"❌ Failed to record action: {e}")
            except Exception:
                pass

    async def _analyze_action_patterns(self) -> None:
        """
        Analyze user action patterns safely (optimized + production-grade)
        """

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            history = getattr(self, "user_action_history", [])
            if not history or len(history) < 20:
                return

            # ------------------------
            # 🔁 NORMALIZE + COUNT
            # ------------------------
            action_counts = {}

            for entry in history[-50:]:
                if not isinstance(entry, dict):
                    continue

                if entry.get("type") != "action":
                    continue

                action = entry.get("action")
                if not action or not isinstance(action, str):
                    continue

                action_key = action.strip().lower()
                if not action_key:
                    continue

                action_counts[action_key] = action_counts.get(action_key, 0) + 1

            if not action_counts:
                return

            # ------------------------
            # 🔥 SORT BY FREQUENCY (CRITICAL FIX)
            # ------------------------
            sorted_actions = sorted(
                action_counts.items(), key=lambda x: x[1], reverse=True
            )

            active = getattr(self, "active_suggestions", [])

            # ------------------------
            # 🧠 GENERATE SUGGESTIONS
            # ------------------------
            for action, count in sorted_actions:

                if count < 5:
                    continue

                title = f"Optimize {action}"

                # ------------------------
                # 🔁 DEDUPLICATION
                # ------------------------
                if any(getattr(s, "title", None) == title for s in active):
                    continue

                try:
                    suggestion = CuriositySuggestion(
                        title=title,
                        description=f"You frequently perform '{action}'. Want to optimize or automate it?",
                        suggestion_type=CuriosityType.OPTIMIZATION,
                        priority=SuggestionPriority.MEDIUM,
                        confidence=min(0.9, 0.5 + (count * 0.05)),
                        tags=["optimization", "automation", "pattern"],
                    )

                    active.append(suggestion)

                    # limit to avoid spam
                    if len(active) > 20:
                        active[:] = active[-20:]

                    break  # only one suggestion per run

                except Exception:
                    continue

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.pattern_insights = getattr(self, "pattern_insights", 0) + 1
            except Exception:
                pass

        except Exception as e:
            try:
                logger.debug(f"Action pattern analysis error: {e}")
            except Exception:
                pass

    # ------------------------
    # REAL EXPLORATION 🔥
    # ------------------------
    async def explore(self, item: CuriosityItem) -> Dict[str, Any]:
        """
        Explore a curiosity topic safely (optimized + production-grade)
        """

        import time
        from datetime import datetime
        import asyncio

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not item or not hasattr(item, "topic"):
                return {"error": "invalid_item"}

            topic = str(item.topic).strip()
            if not topic:
                return {"error": "invalid_topic"}

            # ------------------------
            # ⏱️ COOLDOWN (CRITICAL FIX)
            # ------------------------
            now = time.time()
            if now - getattr(self, "_last_exploration_time", 0) < getattr(
                self, "_exploration_cooldown", 0
            ):
                return {"status": "cooldown", "message": "Exploration on cooldown"}

            self._last_exploration_time = now

            # ------------------------
            # 🔁 DUPLICATE CHECK
            # ------------------------
            explored = getattr(self, "explored_topics", set())
            if topic.lower() in {t.lower() for t in explored}:
                return {"status": "already_explored", "topic": topic}

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.info(f"🔍 Exploring: {topic}")
            except Exception:
                pass

            # ------------------------
            # 🔥 RESEARCH WITH TIMEOUT
            # ------------------------
            try:
                researcher = self._ensure_researcher()
                if researcher:
                    research = await asyncio.wait_for(
                        researcher.research(topic), timeout=10
                    )
                else:
                    research = {"error": "researcher_unavailable", "topic": topic}
            except asyncio.TimeoutError:
                research = {"error": "research_timeout", "topic": topic}
            except Exception as e:
                research = {"error": str(e), "topic": topic}

            # ------------------------
            # 🔁 NORMALIZE RESULT
            # ------------------------
            if research is None:
                research = {}

            if not isinstance(research, dict):
                research = {"data": str(research)}

            result = {
                "topic": topic,
                "data": research,
                "type": getattr(item.curiosity_type, "value", "unknown"),
                "timestamp": datetime.now().isoformat(),
                "source": getattr(item, "source", "unknown"),
                "priority": getattr(item, "priority", 2),
            }

            # ------------------------
            # 🔥 UPDATE ITEM STATE
            # ------------------------
            try:
                item.explored = True
                item.result = result
            except Exception:
                pass

            # ------------------------
            # 📊 TRACKING
            # ------------------------
            try:
                self.explored_topics = getattr(self, "explored_topics", set())
                self.explored_topics.add(topic)

                self.learning_history = getattr(self, "learning_history", [])
                self.learning_history.append(result)

                # limit history
                if len(self.learning_history) > 500:
                    self.learning_history = self.learning_history[-500:]

                self.exploration_count = getattr(self, "exploration_count", 0) + 1
                self._insights_generated = getattr(self, "_insights_generated", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 🧠 MEMORY STORE (SAFE)
            # ------------------------
            try:
                if getattr(self, "memory", None) and hasattr(self.memory, "store"):
                    await asyncio.wait_for(self.memory.store(result), timeout=2)
            except Exception:
                pass

            return result

        except Exception as e:
            try:
                logger.error(f"❌ Exploration failed: {e}")
            except Exception:
                pass

            return {"error": str(e), "topic": getattr(item, "topic", None)}

    # ------------------------
    # SAFE GENERATION
    # ------------------------
    async def generate_curiosity(self) -> None:
        """
        Generate limited curiosity safely (optimized + production-grade)
        """

        try:
            # ------------------------
            # 🔥 FETCH MEMORY (SAFE)
            # ------------------------
            memory_data = []

            try:
                if getattr(self, "memory", None) and hasattr(self.memory, "get_recent"):
                    memory_data = await self.memory.get_recent(3)
            except Exception:
                memory_data = []

            # ------------------------
            # 🔁 NORMALIZE TOPICS
            # ------------------------
            topics = []

            if not memory_data:
                topics = ["AI basics", "productivity tips"]
            else:
                for item in memory_data[:2]:
                    try:
                        text = str(item).strip()
                        if text:
                            topics.append(text[:30])
                    except Exception:
                        continue

            # ------------------------
            # 🔥 DEDUPLICATION SET
            # ------------------------
            existing = {t.lower() for t in getattr(self, "explored_topics", set())}

            # also avoid queue duplicates
            queue_topics = {
                getattr(q, "topic", "").lower() for q in getattr(self, "queue", [])
            }

            # ------------------------
            # 🧠 ADD CURIOSITY (SAFE)
            # ------------------------
            added = 0
            max_items = 2  # SAFE MODE LIMIT

            for t in topics:
                if added >= max_items:
                    break

                topic = f"learn: {t}".strip()
                topic_key = topic.lower()

                if topic_key in existing or topic_key in queue_topics:
                    continue

                try:
                    self.add_curiosity(
                        topic=topic,
                        source="memory",
                        ctype=CuriosityType.LEARNING,
                        priority=3,
                    )
                    added += 1
                except Exception:
                    continue

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.curiosity_generated = (
                    getattr(self, "curiosity_generated", 0) + added
                )
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(f"🧠 Curiosity generated: {added} items")
            except Exception:
                pass

        except Exception as e:
            try:
                logger.debug(f"Curiosity generation error: {e}")
            except Exception:
                pass

    # ------------------------
    # TASK-BASED CURIOSITY
    # ------------------------
    async def suggest_next_action(self, current_task: str) -> Optional[str]:
        """Suggest next action based on current task"""
        try:
            # Simple pattern matching
            task_lower = current_task.lower()

            if "code" in task_lower or "programming" in task_lower:
                return "Consider testing or debugging your code."
            elif "research" in task_lower or "search" in task_lower:
                return "Would you like me to summarize the findings?"
            elif "learn" in task_lower or "study" in task_lower:
                return "Take notes on key concepts for better retention."
            elif "write" in task_lower or "document" in task_lower:
                return "Review your writing for clarity and completeness."
            else:
                return None

        except Exception:
            return None

    async def analyze_task(self, task: str) -> List[Dict[str, Any]]:
        """
        Analyze task and generate suggestions safely (optimized + production-grade)
        """

        suggestions: List[Dict[str, Any]] = []

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not task or not isinstance(task, str):
                return []

            task = task.strip()
            if not task:
                return []

            # ------------------------
            # 🔁 TASK-BASED SUGGESTIONS
            # ------------------------
            try:
                task_suggestions = await self.generate_suggestions(task, limit=3)

                for s in task_suggestions or []:
                    try:
                        if hasattr(s, "to_dict"):
                            data = s.to_dict()
                        elif isinstance(s, dict):
                            data = s
                        else:
                            continue

                        # deduplicate by title
                        if not any(
                            existing.get("title") == data.get("title")
                            for existing in suggestions
                        ):
                            suggestions.append(data)

                    except Exception:
                        continue

            except Exception:
                pass

            # ------------------------
            # 🔥 EXPLORATION SUGGESTIONS
            # ------------------------
            try:
                queue = getattr(self, "queue", [])

                for item in queue[:2]:
                    if not hasattr(item, "topic"):
                        continue

                    title = f"Learn about {item.topic}"

                    # deduplicate
                    if any(s.get("title") == title for s in suggestions):
                        continue

                    suggestions.append(
                        {
                            "type": "exploration",
                            "title": title,
                            "description": f"Based on your interests, explore {item.topic}",
                            "confidence": float(getattr(self, "curiosity_level", 0.5)),
                        }
                    )

            except Exception:
                pass

            # ------------------------
            # 🎯 LIMIT RESULTS
            # ------------------------
            max_results = 5
            suggestions = suggestions[:max_results]

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.task_analyses = getattr(self, "task_analyses", 0) + 1
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(
                    f"🧠 Task analyzed: {task[:50]} ({len(suggestions)} suggestions)"
                )
            except Exception:
                pass

            return suggestions

        except Exception as e:
            try:
                logger.debug(f"Task analysis error: {e}")
            except Exception:
                pass

            return []

    # ------------------------
    # MAIN LOOP 🔥 (FIXED)
    # ------------------------
    async def run(self, interval: float = 5.0):
        """
        SAFE curiosity loop (ultra-stable + production-grade)
        """

        import asyncio
        import time

        try:
            # ------------------------
            # 🔁 ALREADY RUNNING CHECK
            # ------------------------
            if getattr(self, "_running", False):
                return

            self._running = True

            try:
                logger.info("🧠 Curiosity engine (PRODUCTION MODE) running")
            except Exception:
                pass

            last_run = 0
            COOLDOWN = 10

            # ------------------------
            # 🔄 MAIN LOOP
            # ------------------------
            while getattr(self, "_running", False):

                try:
                    now = time.time()

                    # ------------------------
                    # ❤️ HEARTBEAT
                    # ------------------------
                    self._last_heartbeat = now

                    # ------------------------
                    # 💤 IDLE CHECK (SAFE)
                    # ------------------------
                    try:
                        system = getattr(self, "system", None)
                        idle_controller = getattr(system, "idle_controller", None)

                        if idle_controller and hasattr(idle_controller, "is_idle"):
                            is_idle = idle_controller.is_idle
                            if callable(is_idle):
                                is_idle = is_idle()

                            if not is_idle:
                                await asyncio.sleep(2)
                                continue

                    except Exception:
                        pass

                    # ------------------------
                    # ⏱️ COOLDOWN CONTROL
                    # ------------------------
                    if now - last_run < COOLDOWN:
                        await asyncio.sleep(1.5)
                        continue

                    # ------------------------
                    # 🎲 RANDOM TRIGGER (LOW LOAD)
                    # ------------------------
                    if random.random() > 0.03:
                        await asyncio.sleep(interval)
                        continue

                    last_run = now

                    # ------------------------
                    # 🔥 GENERATE TASK (SAFE)
                    # ------------------------
                    try:
                        if not getattr(self, "queue", None):
                            await self.generate_curiosity()
                    except Exception:
                        pass

                    # ------------------------
                    # 🚀 EXECUTE SINGLE TASK (SAFE + TIMEOUT)
                    # ------------------------
                    queue = getattr(self, "queue", [])

                    if queue:
                        try:
                            item = queue.pop(0)

                            await asyncio.wait_for(self.explore(item), timeout=15)

                        except asyncio.TimeoutError:
                            try:
                                logger.warning("⏱️ Curiosity exploration timeout")
                            except Exception:
                                pass

                        except Exception:
                            pass

                    # ------------------------
                    # ⏳ SMART SLEEP (JITTER)
                    # ------------------------
                    sleep_time = interval + random.uniform(-0.5, 0.5)
                    await asyncio.sleep(max(1.0, sleep_time))

                except asyncio.CancelledError:
                    break

                except Exception as e:
                    try:
                        logger.error(f"Curiosity loop error: {e}")
                    except Exception:
                        pass

                    await asyncio.sleep(2)

        finally:
            # ------------------------
            # 🛑 CLEAN SHUTDOWN
            # ------------------------
            self._running = False

            try:
                logger.info("🛑 Curiosity engine stopped")
            except Exception:
                pass

    # ------------------------
    # CONTROL
    # ------------------------
    def stop(self):
        self._running = False

    async def start(self) -> bool:
        """
        Start curiosity engine safely (production-grade)
        """

        try:
            # ------------------------
            # 🔁 ALREADY RUNNING CHECK
            # ------------------------
            if getattr(self, "_running", False):
                try:
                    logger.warning("⚠ Curiosity engine already running")
                except Exception:
                    pass
                return False

            # ------------------------
            # 🔥 CREATE TASK (TRACKED)
            # ------------------------
            try:
                self._task = asyncio.create_task(self.run(), name="curiosity-engine")
            except Exception:
                self._task = asyncio.create_task(self.run())

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.started_at = (
                    getattr(self, "started_at", None) or __import__("time").time()
                )
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.info("🚀 Curiosity engine started")
            except Exception:
                pass

            return True

        except Exception as e:
            try:
                logger.error(f"❌ Failed to start curiosity engine: {e}")
            except Exception:
                pass

            return False

    async def initialize(self, *args, **kwargs):
        """Initialize curiosity engine - for orchestrator compatibility"""
        logger.info("Curiosity engine initialized")
        return True

    # ------------------------
    # SUGGEST
    # ------------------------
    def suggest_exploration(self) -> Optional[str]:
        if self.queue:
            return self.queue[0].topic
        return None

    async def get_recommendations(self, limit: int = 5) -> List[Dict[str, Any]]:
        """
        Get curiosity recommendations safely (optimized + production-grade)
        """

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            try:
                limit = int(limit)
                limit = max(1, min(limit, 20))  # clamp
            except Exception:
                limit = 5

            recommendations: List[Dict[str, Any]] = []

            # ------------------------
            # 🔁 DEDUP SET
            # ------------------------
            seen = set()

            # ------------------------
            # 🔥 QUEUE-BASED
            # ------------------------
            try:
                queue = getattr(self, "queue", [])

                for item in queue:
                    if len(recommendations) >= limit:
                        break

                    topic = getattr(item, "topic", None)
                    if not topic:
                        continue

                    topic_key = str(topic).lower()
                    if topic_key in seen:
                        continue

                    seen.add(topic_key)

                    recommendations.append(
                        {
                            "topic": topic,
                            "type": getattr(
                                getattr(item, "curiosity_type", None),
                                "value",
                                "unknown",
                            ),
                            "priority": getattr(item, "priority", 2),
                            "source": getattr(item, "source", "unknown"),
                        }
                    )

            except Exception:
                pass

            # ------------------------
            # 🔥 GENERIC FALLBACK
            # ------------------------
            if len(recommendations) < limit:
                generic_topics = [
                    "AI trends",
                    "productivity hacks",
                    "learning techniques",
                    "automation tools",
                    "focus improvement",
                ]

                explored = {t.lower() for t in getattr(self, "explored_topics", set())}

                for topic in generic_topics:
                    if len(recommendations) >= limit:
                        break

                    topic_key = topic.lower()

                    if topic_key in seen or topic_key in explored:
                        continue

                    seen.add(topic_key)

                    recommendations.append(
                        {
                            "topic": topic,
                            "type": "exploration",
                            "priority": 3,
                            "source": "system",
                        }
                    )

            # ------------------------
            # 📊 METRICS
            # ------------------------
            try:
                self.recommendations_generated = getattr(
                    self, "recommendations_generated", 0
                ) + len(recommendations)
            except Exception:
                pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                logger.debug(f"📌 Generated {len(recommendations)} recommendations")
            except Exception:
                pass

            return recommendations

        except Exception as e:
            try:
                logger.error(f"❌ Recommendation generation failed: {e}")
            except Exception:
                pass

            return []

    # ------------------------
    # FEEDBACK INTEGRATION
    # ------------------------
    async def record_feedback(
        self, suggestion_id: str, feedback: Optional[str] = None
    ) -> bool:
        """
        Record feedback for a suggestion safely (optimized + production-grade)
        """

        from datetime import datetime

        try:
            # ------------------------
            # 🔥 VALIDATION
            # ------------------------
            if not suggestion_id or not isinstance(suggestion_id, str):
                return False

            updated = False

            # ------------------------
            # 🔁 SEARCH HISTORY (SAFE)
            # ------------------------
            try:
                history = getattr(self, "suggestion_history", [])

                for suggestion in history:
                    if getattr(suggestion, "suggestion_id", None) == suggestion_id:
                        suggestion.feedback = feedback
                        suggestion.feedback_at = datetime.now().isoformat()
                        updated = True
                        break
            except Exception:
                pass

            # ------------------------
            # 🔁 SEARCH ACTIVE (SAFE)
            # ------------------------
            try:
                active = getattr(self, "active_suggestions", [])

                for suggestion in active:
                    if getattr(suggestion, "suggestion_id", None) == suggestion_id:
                        suggestion.feedback = feedback
                        suggestion.feedback_at = datetime.now().isoformat()
                        updated = True
                        break
            except Exception:
                pass

            # ------------------------
            # 🧠 LEARNING STORE (UPGRADE)
            # ------------------------
            if updated:
                try:
                    self.learning_history = getattr(self, "learning_history", [])
                    self.learning_history.append(
                        {
                            "type": "feedback",
                            "suggestion_id": suggestion_id,
                            "feedback": feedback,
                            "timestamp": datetime.now().isoformat(),
                        }
                    )

                    # limit history
                    if len(self.learning_history) > 500:
                        self.learning_history = self.learning_history[-500:]
                except Exception:
                    pass

            # ------------------------
            # 📊 METRICS
            # ------------------------
            if updated:
                try:
                    self.feedback_count = getattr(self, "feedback_count", 0) + 1
                except Exception:
                    pass

            # ------------------------
            # 📢 LOG
            # ------------------------
            try:
                if updated:
                    logger.debug(f"💬 Feedback recorded for {suggestion_id}")
                else:
                    logger.debug(f"⚠ Feedback target not found: {suggestion_id}")
            except Exception:
                pass

            return updated

        except Exception as e:
            try:
                logger.error(f"❌ Feedback recording failed: {e}")
            except Exception:
                pass

            return False

    # ------------------------
    # STATS
    # ------------------------
    def get_stats(self) -> Dict[str, Any]:
        """
        Get curiosity engine stats (safe + production-grade)
        """

        import time

        try:
            # ------------------------
            # 🔒 SAFE ACCESS
            # ------------------------
            explored_topics = getattr(self, "explored_topics", set()) or set()
            queue = getattr(self, "queue", []) or []
            learning_history = getattr(self, "learning_history", []) or []
            active_suggestions = getattr(self, "active_suggestions", []) or []
            task_patterns = getattr(self, "task_patterns", {}) or {}

            stats = {
                "explored_topics": len(explored_topics),
                "queue_size": len(queue),
                "learning_history": len(learning_history),
                "curiosity_level": float(getattr(self, "curiosity_level", 0.0)),
                "exploration_count": int(getattr(self, "exploration_count", 0)),
                "suggestion_count": int(getattr(self, "suggestion_count", 0)),
                "active_suggestions": len(active_suggestions),
                "current_task": getattr(self, "current_user_task", None),
                "current_action": getattr(self, "current_user_action", None),
                # 🔥 SAFE COPY + LIMIT
                "task_patterns": dict(list(task_patterns.items())[:5]),
                "insights_generated": int(getattr(self, "_insights_generated", 0)),
                "status": "running" if getattr(self, "_running", False) else "stopped",
                "memory_available": getattr(self, "memory", None) is not None,
                "researcher_available": getattr(self, "researcher", None) is not None,
                # 📊 EXTRA METRICS (UPGRADE)
                "queue_load": round(
                    len(queue) / max(1, len(queue) + len(explored_topics)), 3
                ),
                "suggestion_ratio": round(
                    len(active_suggestions)
                    / max(1, getattr(self, "suggestion_count", 1)),
                    3,
                ),
                "timestamp": time.time(),
            }

            return stats

        except Exception as e:
            try:
                if hasattr(self, "logger"):
                    self.logger.error(f"Stats error: {e}")
            except Exception:
                pass

            return {"error": "stats_failed", "timestamp": time.time()}

    def get_learning_summary(self) -> Dict[str, Any]:
        """Get summary of learning activities"""
        return {
            "total_explorations": self.exploration_count,
            "total_suggestions": self.suggestion_count,
            "unique_topics": len(self.explored_topics),
            "recent_learnings": (
                self.learning_history[-5:] if self.learning_history else []
            ),
        }

    def get_performance_metrics(self) -> Dict[str, Any]:
        """
        Get performance metrics safely (optimized + production-grade)
        """

        import time

        try:
            now = time.time()

            # ------------------------
            # 🔒 SAFE VALUES
            # ------------------------
            last_heartbeat = getattr(self, "_last_heartbeat", None)
            insights = int(getattr(self, "_insights_generated", 0))
            suggestions = int(getattr(self, "suggestion_count", 0))

            # ------------------------
            # ⏱️ UPTIME (SAFE)
            # ------------------------
            uptime = (now - last_heartbeat) if last_heartbeat else 0.0
            uptime = max(0.0, uptime)

            minutes = uptime / 60 if uptime > 0 else 0
            hours = uptime / 3600 if uptime > 0 else 0

            # ------------------------
            # 📊 METRICS
            # ------------------------
            insights_per_min = insights / minutes if minutes > 0 else 0.0

            suggestion_rate = suggestions / hours if hours > 0 else 0.0

            # ------------------------
            # 🔥 BUILD RESPONSE
            # ------------------------
            metrics = {
                "uptime_seconds": round(uptime, 2),
                "uptime_minutes": round(minutes, 2),
                "insights_generated": insights,
                "suggestions_generated": suggestions,
                "insights_per_minute": round(insights_per_min, 2),
                "suggestion_rate_per_hour": round(suggestion_rate, 2),
                "efficiency_score": (
                    round((insights_per_min * 0.7 + suggestion_rate * 0.3), 2)
                    if uptime > 0
                    else 0.0
                ),
                "timestamp": now,
            }

            return metrics

        except Exception as e:
            try:
                logger.error(f"❌ Performance metrics failed: {e}")
            except Exception:
                pass

            return {"error": "metrics_failed", "timestamp": time.time()}


__all__ = [
    "CuriosityEngine",
    "CuriosityItem",
    "CuriosityType",
    "CuriositySuggestion",
    "SuggestionPriority",
]
